### ISSUE TITLE
Desenvolver sistema de monitoramento em tempo real

### ISSUE THREAD

**Issue by ChrysH2000** [ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-gps-202402-9247101-smart-pantry#10]
Responsável: Chrystian Fonseca (Dev Sênior) 
o Requisito Funcional: Implementar monitoramento dos estoques e sensores 
em tempo real. 
o Requisito Não Funcional: Garantir escalabilidade e precisão na coleta de 
dados.

**Comment by samarahellen** [comment]
-Definição de inicio e fim da tarefa.
