### ISSUE TITLE
Estabelecer escopo do projeto

### ISSUE THREAD

**Issue by IgorRattes** [ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-gps-202402-9247101-smart-pantry#2]
o	Responsável: João Silva (Gerente de Projeto)
o	Requisito Funcional: Definir funcionalidades e escopo geral do sistema.
o	Requisito Não Funcional: Estabelecer diretrizes de desempenho e segurança.

**Comment by samarahellen** [comment]
-Levantamento de informações dos stakeholders 
-Documentação do escopo em andamento
