### ISSUE TITLE
Desenho da arquitetura do sistema

### ISSUE THREAD

**Issue by IgorRattes** [ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-gps-202402-9247101-smart-pantry#4]
o	Responsável: @ChrysH2000  (Dev Sênior)
o	Requisito Funcional: Especificar módulos e componentes do sistema.
o	Requisito Não Funcional: Proporcionar uma arquitetura escalável e modular.

**Comment by samarahellen** [comment]
-Definição de inicio e fim da tarefa.
