### ISSUE TITLE
Consultoria de sustentabilidade e avaliação

### ISSUE THREAD

**Issue by IgorRattes** [ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-gps-202402-9247101-smart-pantry#5]
o	Responsável: Leonardo Santos (Consultor Externo)
o	Requisito Funcional: Avaliar a sustentabilidade do projeto e propor melhorias.
o	Requisito Não Funcional: Promover práticas que reduzam o impacto ambiental do sistema.

**Comment by samarahellen** [comment]
-Pesquisa de práticas sustentáveis para aplicação no projeto.
